### PR TITLE
GPII-1558:  Update handler to allow alternate uses of `sendResponse`…

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1558](https://issues.gpii.net/browse/GPII-1558) for details.

### CODE REVIEW

**Comment by amb26** [comment]
The grunt configuration of this project is corrupt in that it refers to the grunt-gpii task which is no longer a dependency, which prevents it bring linted

**Comment by amb26** [comment]
Should take this opportunity to give package.json a general spring cleaning - 
  - proper version number
  - correct repo reference, etc.

**Comment by the-t-in-rtf** [comment]
Tidied up both and merged in previous fixes to `Gruntfile.js` already in `master`.

**Comment by the-t-in-rtf** [comment]
@amb26, I am preparing a new PR for [GPII-1647](https://issues.gpii.net/browse/GPII-1647).  As we appear to be done here, it would be helpful to merge this one just to keep that conversation clear.

**Comment by the-t-in-rtf** [comment]
Closed in favor of a later PR: https://github.com/GPII/gpii-express/pull/20

**Pull request closed without merging**
