### PR TITLE
GPII-1179:  Initial implementation and tests for `contentAware` router.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1179](https://issues.gpii.net/browse/GPII-1179) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
We discussed this in depth, and agreed that this model needs to be similar to what is done with router.  To that end, I will refactor to make the list of options consist of content types and requestAwareGrades.  The router will construct an appropriate handler and pass the request on to it, just as another requestAwareRouter would.

**Comment by the-t-in-rtf** [comment]
After a long pause, I realized that the request grade should not be responsible for brokering this, but that a plain old `gpii.express.router` would be better suited.  This approach allows mashing up existing `requestAware.router` grades to service a single end point.

**Comment by the-t-in-rtf** [comment]
The tests for the content aware router are currently failing with a "maximum stack size" error.

**Comment by the-t-in-rtf** [comment]
The component and all tests are working again and this is ready for review.

**Comment by amb26** [comment]
Closed for #10 which incorporates all this material where it will be reviewed

**Pull request closed without merging**
